### ISSUE TITLE
Set map maxZoom to 17 and minZoom to 8

### ISSUE THREAD

**Issue by davidheyman** [axismaps/highways-waterways#10]

**Comment by davidheyman** [comment]
I tried this in 53cd06f8 but couldn't get it to work. Not sure if it's being overridden somewhere else.

**Comment by DaviTeodoro** [comment]
Dave, its is not been overridden anywhere else, it looks like it is working as expected.. dont know.. For instance I tried it with min and max to 12 and it kept the map locked at 12, as expected. 

So, I try some values and find out that min zoom level at 10, IMO, works better.  I made this change here (b3481bf13152dc5d9dcfe744aebc763075a6418b). See what you think
