### ISSUE TITLE
Download button should download image of map

### ISSUE THREAD

**Issue by davidheyman** [axismaps/highways-waterways#15]
@awoodruff Is the _expert_ at this. He loves print / download buttons so much and will be happy to point you in the right direction.

**Comment by awoodruff** [comment]
Oh hooray, my favorite thing!

This uses mapbox, right? If it's just a map image, the map canvas can be exported to PNG as long as the `preserveDrawingBuffer` option is `true` in the map initialization. If we need higher resolution, there's a good method here: https://github.com/mpetroff/print-maps. (I recently tried a simple implementation of that here: https://github.com/axismaps/ipc-demo/blob/image-export/app/scripts/export.js)

If other screen elements need to be drawn on the image, I've had some success with [rasterizeHTML](https://www.npmjs.com/package/rasterizehtml) and basic steps like this:
1. clone the element and append the clone to the document (remove at the end, of course)
2. add all relevant CSS styles inline; the rasterize method doesn't pick up styles from external CSS
3. generate raster (e.g. `rasterizeHTML.drawHTML(clone.outerHTML)`)
4. assemble the various canvas elements (rasterized HTML elements plus map image) onto a final canvas for export

**Comment by DaviTeodoro** [comment]
hahaha ok I'll be working on it

**Comment by DaviTeodoro** [comment]
@awoodruff  would you min give me access to https://github.com/axismaps/ipc-demo/blob/image-export/app/scripts/export.js? I dont have it. Or just post the script here. Thank you =)

**Comment by davidheyman** [comment]
That’s done now. Let me know if you still don’t have access.

**Comment by DaviTeodoro** [comment]
this one should solve it 397365526cc59a80952ac941692b613536d13c0b
