### ISSUE TITLE
Slider layer functionality (choropleth, flood raster, etc) 

### ISSUE THREAD

**Issue by bwellington** [axismaps/highways-waterways#5]
This is also waiting on API endpoints. I have value placeholder sliders, but the actual layer functionality is not there. The sliders also still need some additional detail (tooltip, background colors, etc), and range slider functionality is missing.

**Comment by davidheyman** [comment]
@DaviTeodoro This is ready to go with a separate legend API call. Send me a Slack and I'll walk you through the data and the designs.

**Comment by davidheyman** [comment]
Quick change to the double sliders: All thematic layers should start 'off' with the handles fully expanded to min / max. The single sliders should start at the minimum.

**Comment by davidheyman** [comment]
Another change: The on / off switches on the thematic layers need to function like radio buttons so you can only view a single thematic layer at once.

**Comment by DaviTeodoro** [comment]
these two solve it 831d7e9a5a6d2569d49c4e855d4d7bceb14bb3c4 3d3b014bbc72f382c0cb7391f4f881a6a7f9df67

**Comment by davidheyman** [comment]
I'm still not seeing the radio button functionality with this. Only 1 thematic layer should be allowed to be active at once so when you turn one on, the others should turn off.

![2020-02-13_12-15-25 (1)](https://user-images.githubusercontent.com/791434/74434570-9ad69a00-4e5a-11ea-8c69-7a699c21dff5.gif)

**Comment by DaviTeodoro** [comment]
this one fixes it 92fd7849b72687cfd2d7c7efeb63c7658af6d0d2

**Comment by davidheyman** [comment]
This is looking better. One last thing and it is done. Unlike a regular radio button, you need to be able to turn all the layers off as well. Currently, once a layer is on, the only way to turn it off is to turn on a different layer.

**Comment by DaviTeodoro** [comment]
this one should do it 96ec060e6cd0623f7784354d1039f881eb2f0fa0
