### ISSUE TITLE
Non-slider thematic layers

### ISSUE THREAD

**Issue by davidheyman** [axismaps/highways-waterways#7]
For thematic layers that have `NULL` as the slider type, these should display using the same legend type and functionality as appears in the main layers where the Types are listed below the layer name. Like other thematic layers in #5, they should default to being 'off'.

**Comment by DaviTeodoro** [comment]
this one solves it 92fd7849b72687cfd2d7c7efeb63c7658af6d0d2, but we are not getting styling data with ids f257fad2-3461-4c25-89aa-210904047543 (chemical composition) and dc003439-3421-424b-bcbf-7c52ebceb596 (311 Complaints)
